# Generated by Django 4.0.1 on 2022-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='nom',
            field=models.DateTimeField(),
        ),
    ]
