# Generated by Django 4.0.1 on 2022-01-28 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
