# Generated by Django 4.0.1 on 2022-02-03 15:26

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_experience_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='nom',
            new_name='poste',
        ),
        migrations.AddField(
            model_name='experience',
            name='end',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
            ],
        ),
    ]
