# Generated by Django 4.0.1 on 2022-02-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_rename_nom_experience_poste_experience_end_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Missions',
            new_name='Mission',
        ),
    ]
